version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: adsp_mds_demaniodigitale_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: adspadmin
      POSTGRES_PASSWORD: Nexus2025!
      POSTGRES_DB: adsp_mds_demaniodigitale
    ports:
      - "5432:5432"
    volumes:
      - adsp_mds_demaniodigitale_db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend/AdspMds.Api
      dockerfile: Dockerfile
    container_name: adsp_mds_demaniodigitale_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=adsp_mds_demaniodigitale;Username=adspadmin;Password=Nexus2025!
      Jwt__Key: 5n9kV1Aq3Lx2Rz7Hf4Qp8sDd0Jt6eKcN
      Jwt__Issuer: identity.demaniodigitale.adspmaredisardegna.it
      Jwt__Audience: demaniodigitale.adspmaredisardegna.it
      Seed__AdminEmail: admin@local.test
      Seed__AdminPassword: Nexus2025!
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./backend/AdspMds.Api:/src
    working_dir: /src
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: adsp_mds_demaniodigitale_frontend
    environment:
      NODE_ENV: development
    ports:
      - "4200:4200"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - adsp_mds_demaniodigitale_frontend_node_modules:/app/node_modules
    working_dir: /app
    command: ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200", "--disable-host-check"]

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: adsp_mds_demaniodigitale_nginx
    depends_on:
      - api
      - frontend
    ports:
      - "443:443"

volumes:
  adsp_mds_demaniodigitale_db_data:
  adsp_mds_demaniodigitale_frontend_node_modules:
